#! /bin/sh
# Copyright (c) 2013 Ryan Mueller
# All rights reserved.
#
# Author: Ryan Mueller, 2013
#
### BEGIN INIT INFO
# Provides:	nes-keypress
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Starts NES controller drivers
# Description: Starts the NES controller drivers
### END INIT INFO

# Start nes-keypress
case "$1" in
  start)
      python /usr/bin/nes-keypress.py -if /.nes-keypress/controller1.json
	  python /usr/bin/nes-keypress.py -if /.nes-keypress/controller2.json
      ;;
  stop|restart|reload|status)
      echo "Operation not supported"
      ;;
esac
